spring:
  datasource:
    url: ${env.datasource.url}
    username: ${env.datasource.username}
    password: ${env.datasource.password}
    driver-class-name: ${env.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${env.jpa.ddl-auto}
    show-sql: ${env.jpa.show-sql:false}
    properties:
      hibernate:
        format_sql: ${env.jpa.format_sql:false}

discord:
  token: ${env.discord.token}
  extra-tokens: ${env.discord.extra-token-1:},${env.discord.extra-token-2:},${env.discord.extra-token-3:}

app:
  jwt:
    secret: ${env.jwt.secret}
    expiration: ${env.jwt.expiration:3600000}

logging:
  level:
    root: ${env.logging.root:INFO}
    com.discord: ${env.logging.com-discord:INFO}
    dev.arbjerg.lavalink: ${env.logging.lavalink:INFO}
